### ISSUE TITLE
Bug: parchmint throws keyError when certain key is not detected in json

### ISSUE THREAD

**Issue by bjoernh2000** [CIDARLAB/pyparchmint#2]
```
File "/home/ubuntu/pyparchmint/parchmint/device.py", line 228, in parse_from_json
    for layer in json["layers"]:
KeyError: 'layers'
```

3DuF didn't generate the 'layers' key for the JSON object, and on parsing the file into parchmint a key error is thrown.

**Comment by rkrishnasanka** [comment]
@bjoernh2000 this probably needs to extend for more cases too. Like when no `connections`, `components`, `params` keys are found. When printing the error, it should account for the detail where the object tree this error is coming from.
